apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  clusterIP: None
  selector:
    app: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment
        env:
          - name: APPLICATION_PORT
            value : "8081"
          - name: ENV
            value: "development"
          - name: DATA_SOURCE_URL
            value : "root:s3cr3t@tcp(mysql:3306)/payments?charset=utf8mb4&parseTime=True&loc=Local"
